### ISSUE TITLE
Update vague prior for normal vignette

### ISSUE THREAD

**Issue by abiterry** [GSK-Biostatistics/beastt#66]
@nwbean #65 

Vague prior is mentioned on lines

- https://github.com/GSK-Biostatistics/beastt/blob/cfc4eefa07619ba506754459b0c70d861d1dccec/vignettes/continuous.Rmd#L91
- https://github.com/GSK-Biostatistics/beastt/blob/cfc4eefa07619ba506754459b0c70d861d1dccec/vignettes/continuous.Rmd#L98
- https://github.com/GSK-Biostatistics/beastt/blob/cfc4eefa07619ba506754459b0c70d861d1dccec/vignettes/continuous.Rmd#L119
- https://github.com/GSK-Biostatistics/beastt/blob/cfc4eefa07619ba506754459b0c70d861d1dccec/vignettes/continuous.Rmd#L143

**Comment by nwbean** [comment]
Let's change the mean from 50 to 0.50 which should better correspond to the data.

Additionally, can we change the following items:

- In the DATASET.R file, change the seed from 123 to 12345. We simulate the data to have a trt effect of about 0.1, but with the current seed, the data by chance have little treatment effect (and the internal control mean response is pretty different from the external control). The seed 12345 should simulate data for the normal endpoint case that better illustrates the methods in the vignette.

- In the utils.R file, change the plot_dist() function to have a default alpha of 0.5. With the current default option, plots that include multiple priors/posteriors are difficult to read due to lack of transparency in the overlapping distributions.

**Comment by abiterry** [comment]
Following our discussion, I've left the mean as is for the moment and just removed the vague prior from the plot but made the other changes.
